import razorpayInstance from "#config/razorpay.config.js";
import { Cart } from "../cart/cart.model.js";
import { Order } from "./order.model.js";
import { Product } from "../products/product.model.js";
import { User } from "../users/user.model.js";
import CustomError from "#shared/errors/CustomError.util.js";
import crypto from "crypto";

export const createOrderService = async ({ userId, productData }) => {
  const { products, amount, tax, shipping, currency } = productData;

  const options = {
    amount: Math.round(Number(amount) * 100), // Amount in paise
    currency: currency || "INR",
    receipt: `receipt_${Date.now()}`,
  };

  const razorpayOrder = await razorpayInstance.orders.create(options);

  //save order in DB
  const newOrder = new Order({
    userId: userId,
    products,
    amount,
    tax,
    shipping,
    currency,
    status: "pending",
    razorpayOrderId: razorpayOrder.id,
  });
  await newOrder.save();

  return razorpayOrder;
};

export const verifyPaymentService = async ({ userId, razorpayData }) => {
  const {
    razorpay_order_id,
    razorpay_payment_id,
    razorpay_signature,
    paymentFailed,
  } = razorpayData;

  if (paymentFailed) {
    const order = await Order.findOneAndUpdate(
      { razorpayOrderId: razorpay_order_id },
      { status: "failed" },
      { new: true },
    );

    // throw new CustomError(
    //   "Payment failed and order status updated successfully!",
    //   400,
    // );
    return {
      order,
    };
  }

  const expectedSignature = crypto
    .createHmac("sha256", process.env.RAZORPAY_KEY_SECRET)
    //signature is generated by concatenating order_id and payment_id with a pipe (|) separator
    .update(razorpay_order_id + "|" + razorpay_payment_id)
    .digest("hex");

  if (expectedSignature !== razorpay_signature) {
    await Order.findOneAndUpdate(
      { razorpayOrderId: razorpay_order_id },
      { status: "failed" },
      { new: true },
    );

    throw new CustomError(
      "Payment verification failed due to signature mismatch",
      400,
    );
  }

  const order = await Order.findOneAndUpdate(
    { razorpayOrderId: razorpay_order_id },
    {
      status: "paid",
      razorpayPaymentId: razorpay_payment_id,
      razorpaySignature: razorpay_signature,
    },
    { new: true },
  );
  await Cart.findOneAndDelete(
    { userId },
    { $set: { items: [], totalPrice: 0 } },
  );

  return order;
};

export const getMyOrdersService = async ({ userId }) => {
  const orders = await Order.find({ userId })
    .populate({
      path: "products.productId",
      select: "productName productPrice productImg",
    })
    .populate("userId", "firstName lastName email");

  return orders;
};

export const getUserOrdersService = async ({ userId }) => {
  const orders = await Order.find({ userId })
    .populate({
      path: "products.productId",
      select: "productName productPrice productImg",
    })
    .populate("userId", "firstName lastName email");

  return orders;
};

export const getAllOrdersService = async () => {
  const orders = await Order.find()
    .sort({ createdAt: -1 })
    .populate("userId", "firstName lastName email")
    .populate("products.productId", "productName productPrice"); //populate product info

  return orders;
};

export const getSalesDataService = async () => {
  const totalUsers = await User.countDocuments({});
  const totalProducts = await Product.countDocuments({});
  const totalOrders = await Order.countDocuments({ status: "paid" });

  //Total Sales Amount
  const totalSaleAgg = await Order.aggregate([
    { $match: { status: "paid" } },
    { $group: { _id: null, total: { $sum: "$amount" } } },
  ]);

  const totalSales = totalSaleAgg[0]?.total || 0;

  //Sales grouped by date (last 30 days)
  const thirtyDaysAgo = new Date();
  thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);

  const salesByDate = await Order.aggregate([
    { $match: { status: "paid", createdAt: { $gte: thirtyDaysAgo } } },
    {
      $group: {
        _id: { $dateToString: { format: "%Y-%m-%d", date: "$createdAt" } },
        amount: { $sum: "$amount" },
      },
    },
    { $sort: { _id: 1 } }, // Sort by date ascending
  ]);

  const formattedSales = salesByDate.map((item) => ({
    date: item._id,
    amount: item.amount,
  }));

  return { totalUsers, totalProducts, totalOrders, totalSales, formattedSales };
};
